'''The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?'''
import math

def triangNum(num):
    i = 2
    count = 0
    while count <= num:
        i += 1
        triang = int((i/2)*(i+1)) # Gauss's method to get triangular nums
        count = 0
        for n in range(1,int(math.sqrt(triang))+1): # taking the sqrt of the num is the key for the semi_efficient solution
            if triang % n == 0:
                count += 2
    return triang, count
        #if count >= num:
            #return triang

print(triangNum(500))
